# Generated by Django 4.2.7 on 2024-04-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payload_Test',
            new_name='PayloadTest',
        ),
    ]
