# Generated by Django 4.2.7 on 2024-06-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_rename_payload_test_payloadtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PayloadTest',
        ),
    ]
