# Generated by Django 4.2.7 on 2024-06-20 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_payload_delete_payloadtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payload',
            name='event',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='event_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
