# Generated by Django 4.2.7 on 2024-11-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_payload_creation_timestamp_payload_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payload',
            name='event_type',
        ),
    ]
