# Generated by Django 5.0.2 on 2024-04-01 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet_Transactions_History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=1000, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "amount",
                    models.CharField(blank=True, max_length=100000000, null=True),
                ),
                (
                    "is_credit",
                    models.BooleanField(help_text="True for credit, False for debit"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
