# Generated by Django 4.2.7 on 2024-04-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_wallettransaction_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funding_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=5000, null=True)),
                ('total_card_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=5000, null=True)),
            ],
        ),
    ]
