# Generated by Django 4.2.7 on 2024-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_account_total_failed_card_payment_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_wallet_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5000, null=True),
        ),
    ]
