# Generated by Django 4.2.7 on 2024-06-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_custom_timestamp_cryptotransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
