# Generated by Django 4.2.7 on 2024-06-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_wallettransaction_fee_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default='10.00', help_text='This is the fee in percentage to be charged on the amount. Default is 10%', max_digits=50, null=True),
        ),
    ]
