# Generated by Django 4.2.7 on 2024-06-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_wallettransaction_fee_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='is_credit',
            new_name='credit',
        ),
    ]
