# Generated by Django 4.2.7 on 2024-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_is_credit_wallettransaction_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='funded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The amount credited to the user's wallet.", max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The original amount deposited by the user before deducting any charges.', max_digits=50, null=True),
        ),
    ]
