# Generated by Django 4.2.7 on 2024-06-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_wallettransaction_funded_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default='10.00', help_text='This is the fee charged for this transaction.', max_digits=50, null=True),
        ),
    ]
