# Generated by Django 4.2.7 on 2024-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_wallettransaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('WALLET_FUNDING', 'Wallet Funding'), ('CARD_CREATION', 'Card Creation')], max_length=200, null=True),
        ),
    ]
