# Generated by Django 4.2.7 on 2024-06-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='transaction_type',
        ),
    ]
