# Generated by Django 4.2.7 on 2024-06-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotransaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
