# Generated by Django 5.0.2 on 2024-02-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypto_address",
            name="date",
            field=models.CharField(max_length=10000),
        ),
    ]
