# Generated by Django 4.2.7 on 2024-04-09 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_wallet', '0003_alter_crypto_address_coin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crypto_Address',
            new_name='CryptoAddres',
        ),
    ]
