# Generated by Django 4.2.7 on 2024-06-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallet', '0004_rename_crypto_address_cryptoaddres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoAddres',
        ),
    ]
