# Generated by Django 4.2.7 on 2024-06-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto_wallet', '0005_delete_cryptoaddres'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=10000, null=True)),
                ('coin', models.CharField(blank=True, max_length=10000, null=True)),
                ('network_chain', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
