# Generated by Django 4.2.7 on 2024-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallet', '0007_cryptofundingrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptofundingrequest',
            old_name='processed',
            new_name='confirmed',
        ),
        migrations.AddField(
            model_name='cryptofundingrequest',
            name='fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default='10.00', help_text='This is the fee in percentage to be charged on the amount. Default is 10%', max_digits=50, null=True),
        ),
    ]
