# Generated by Django 4.2.7 on 2024-06-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallet', '0008_rename_processed_cryptofundingrequest_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptofundingrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=50, null=True),
        ),
    ]
