# Generated by Django 5.0.2 on 2024-03-05 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=10000)),
                ("card_id", models.CharField(max_length=10000)),
                ("security_code", models.CharField(max_length=3)),
                ("card_expiration", models.CharField(max_length=4)),
                ("balance", models.CharField(max_length=10000)),
                ("status", models.CharField(max_length=10000)),
                ("brand", models.CharField(max_length=10000)),
                ("currency", models.CharField(max_length=10000)),
                ("card_number", models.CharField(max_length=10000)),
                ("creation_date", models.CharField(max_length=10000)),
                ("last_used_date", models.CharField(max_length=10000)),
                ("billing_address_address", models.CharField(max_length=10000)),
                ("billing_address_city", models.CharField(max_length=10000)),
                ("billing_address_state", models.CharField(max_length=10000)),
                ("billing_address_zip_code", models.CharField(max_length=10000)),
                ("billing_address_country", models.CharField(max_length=10000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
