# Generated by Django 5.0.2 on 2024-03-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="card_expiration",
            new_name="card_expiration_date",
        ),
    ]
