# Generated by Django 5.0.2 on 2024-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0002_rename_card_expiration_card_card_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_number_mask",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
