# Generated by Django 5.0.2 on 2024-03-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0003_card_card_number_mask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="full_name",
            new_name="card_full_name",
        ),
        migrations.AddField(
            model_name="card",
            name="card_color",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="user_name",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
