# Generated by Django 4.2.7 on 2024-04-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_card_profit_card_activated_card_amount_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
