# Generated by Django 4.2.7 on 2024-04-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card_Profit',
            new_name='CardProfitDeclaration',
        ),
    ]
