# Generated by Django 4.2.7 on 2024-04-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_rename_card_profit_cardprofitdeclaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprofitdeclaration',
            name='card_maintenance_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='cardprofitdeclaration',
            name='failed_card_payment_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
