# Generated by Django 4.2.7 on 2024-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_cardprofitdeclaration_card_maintenance_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='amount_limit',
        ),
        migrations.RemoveField(
            model_name='card',
            name='billing_address_address',
        ),
        migrations.RemoveField(
            model_name='card',
            name='billing_address_zip_code',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_expiration_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_used_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user_name',
        ),
        migrations.AddField(
            model_name='card',
            name='billing_address_line_1',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='billing_address_postal_code',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, help_text='Note: Time is in Coordinated Universal Time (UTC+00:00)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='billing_address_city',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='billing_address_country',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='billing_address_state',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Note: Time is in Coordinated Universal Time (UTC+00:00)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='security_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
