# Generated by Django 4.2.7 on 2024-05-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_remove_card_amount_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_expiration_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
