# Generated by Django 4.2.7 on 2024-06-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_card_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='credit_account_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
