# Generated by Django 4.2.7 on 2024-06-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_card_credit_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('cancelled', 'cancelled')], max_length=10000, null=True),
        ),
    ]
