# Generated by Django 4.2.7 on 2024-06-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_card_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='activated',
        ),
    ]
