# Generated by Django 4.2.7 on 2024-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_remove_card_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_full_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_number_mask',
        ),
        migrations.RemoveField(
            model_name='card',
            name='credit_account_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.AddField(
            model_name='card',
            name='card_token',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='nickname',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='purpose',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='state',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
