# Generated by Django 4.2.7 on 2024-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_remove_card_card_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='wallet_id',
        ),
        migrations.AddField(
            model_name='card',
            name='card_creation_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
