# Generated by Django 4.2.7 on 2024-10-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_remove_card_wallet_id_card_card_creation_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='billing_address_postal_code',
            new_name='billing_address_zip_code',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='security_code',
            new_name='card_cvv',
        ),
        migrations.AddField(
            model_name='card',
            name='billing_address_line_2',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_masked_number',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_expiration_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
