# Generated by Django 5.1.3 on 2024-11-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_rename_billing_address_postal_code_card_billing_address_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_creation_response_2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
