# Generated by Django 5.1.3 on 2024-11-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_card_card_creation_response_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_creation_response_2',
            new_name='last_card_activity_response',
        ),
    ]
