# Generated by Django 5.0.2 on 2024-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="card_user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
