# Generated by Django 4.2.7 on 2024-04-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet_balance',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
