# Generated by Django 4.2.7 on 2024-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_logindetail_timestamp_alter_profile_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(blank=True, max_length=100, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('access_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('expires_in', models.CharField(blank=True, help_text='Expiry is in seconds.', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Note: Time is in Coordinated Universal Time (UTC+00:00)')),
            ],
        ),
    ]
