# Generated by Django 4.2.7 on 2024-09-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_authtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthToken',
            new_name='AlphaspaceAuthToken',
        ),
    ]
