# Generated by Django 4.2.7 on 2024-11-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_authtoken_alphaspaceauthtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card_user_id',
        ),
    ]
