# Generated by Django 5.1.7 on 2025-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_profile_card_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
